version: "3.9"

services:
  jupyter:
    build: ./core/jupyter
    restart: always
    volumes:
      - ./core/jupyter/notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    depends_on:
      - mongo
    environment:
      - JUPYTER_TOKEN=aip
      - JUPYTER_ENABLE_LAB=yes

  mongo:
    restart: always
    image: "${MONGO_VERSION:-mongo:5.0-focal}"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    network_mode: bridge
    # environment:
    #   MONGO_INITDB_RkVOOT_USERNAME: "${MONGO_USERNAME:-root}"
    #   MONGO_INITDB_ROOT_PASSWORD: "${MONGO_USERNAME:-password}"

volumes:
  db: